apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  labels:
{{- include "enbuild-helm-chart.labels" . | nindent 4 }}
data:
  default.conf: |-
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }

    server {
      listen 8080 default_server;
      server_name _;
      proxy_pass_header Authorization;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      location /enbuild-bk/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-backend/;
      }

      location /enbuild-user/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-user/;
      }

{{- if .Values.enbuildAI.enabled }}

      location /enbuild-ai/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-ai/;
      }
{{- end }}

{{- if .Values.global.headlamp.enabled }}
      location /headlamp/ {
        proxy_pass http://{{ .Release.Name }}-headlamp/headlamp/;
      }

{{- end }}

{{- if .Values.global.monitoring.enabled }}

      location /grafana/ {
        # auth_request /auth-check;
        # error_page 401 = /;
        proxy_pass http://{{ .Release.Name }}-grafana/;
        rewrite ^/grafana/(.*) /$1 break;
     }
{{- end }}
    } # end of server block
