apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  labels:
{{- include "enbuild-helm-chart.labels" . | nindent 4 }}
data:
  default.conf: |-
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }

    server {
      listen 8080 default_server;
      server_name _;
      proxy_pass_header Authorization;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      location /enbuild-bk/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-backend/;
      }

      location /enbuild-user/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-user/;
      }

{{- if .Values.lightning_features.deploy_lightning.ai_lightning }}

      location /enbuild-ai/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-ai/;
      }
{{- end }}

{{- if .Values.lightning_features.operations_lightning.headlamp }}
      location /headlamp/ {
        proxy_pass http://{{ .Release.Name }}-headlamp/headlamp/;
      }

{{- end }}

{{- if .Values.lightning_features.operations_lightning.monitoring }}

      location /grafana/ {
        proxy_pass http://{{ .Release.Name }}-grafana/;
        rewrite ^/grafana/(.*) /$1 break;
     }
{{- end }}

{{- if .Values.lightning_features.develop_lightning.application }}

      location /bolt/ {
          proxy_pass http://{{ .Release.Name }}-bolt/bolt/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
      }
{{- end }}

{{- if .Values.lightning_features.develop_lightning.models }}
        location /jupyter/ {
            proxy_pass http://proxy-public/jupyter/;
            proxy_redirect /hub/ /jupyter/hub/;
            proxy_cookie_path /hub/ /jupyter/hub/;
            sub_filter 'href="/hub/' 'href="/jupyter/hub/';
            sub_filter 'src="/hub/' 'src="/jupyter/hub/';
            sub_filter_once off;
        }
{{- end }}
    } # end of server block
