apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  labels:
{{- include "enbuild-helm-chart.labels" . | nindent 4 }}
data:
  default.conf: |-

    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }
    
    server {
      listen 8080 default_server;
      server_name _;
      proxy_pass_header Authorization;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      location = /auth-check {
          internal;
          # return 200;  # proxy not working with auth_request
          proxy_pass http://{{ .Release.Name }}-enbuild-user/api/v1/roles/auth;

          # Force method = GET
          proxy_pass_request_body off;
          proxy_set_header Content-Length "";

          # Include session info
          proxy_set_header Cookie $http_cookie;
          proxy_set_header Authorization $http_x_auth_token;
          proxy_set_header X-Original-URI $request_uri;
      }

      location /enbuild-bk/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-backend/;
      }

      location /enbuild-user/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-user/;
      }

{{- if .Values.enbuildMl.enabled }}

      location /enbuild-ml/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-ml/;
      }
      {{- if .Values.jupyterhub.cull.enabled }}
      location /jupyter/ {
          proxy_pass http://proxy-public/jupyter/;
          proxy_redirect /hub/ /jupyter/hub/;
          proxy_cookie_path /hub/ /jupyter/hub/;
          sub_filter 'href="/hub/' 'href="/jupyter/hub/';
          sub_filter 'src="/hub/' 'src="/jupyter/hub/';
          sub_filter_once off;
      }
      {{- end }}
{{- end }}

{{- if .Values.enbuildAI.enabled }}

      location /enbuild-ai/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-ai/;
      }
{{- end }}

{{- if .Values.global.headlamp.enabled }}
      location /headlamp/ {
        # auth_request /auth-check;
        # error_page 401 = /;
        proxy_pass http://{{ .Release.Name }}-headlamp/headlamp/;
      }

{{- end }}

{{- if .Values.global.monitoring.enabled }}

      location /grafana/ {
        # auth_request /auth-check;
        # error_page 401 = /;
        proxy_pass http://{{ .Release.Name }}-grafana/;
        rewrite ^/grafana/(.*) /$1 break;
     }
{{- end }}
    } # end of server block