apiVersion: v2
name: enbuild
description: A Helm chart for ENBUILD
type: application
keywords: [enbuild, bigbang]
home: https://www.vivsoft.io/
sources: [https://github.com/jupyterhub/zero-to-jupyterhub-k8s]
icon: https://enbuild-docs.vivplatform.io/images/emma/enbuild-logo.png
kubeVersion: '>=1.25.0-0'
version: 0.0.31
appVersion: 1.0.23
maintainers:
  - name: Juned Memon
    email: jmemon@vivsoft.io
dependencies:
  - name: rabbitmq
    version: 11.13.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: jupyterhub
    version: 3.3.7
    repository: https://jupyterhub.github.io/helm-chart
    condition: lightning_features.develop_lightning.models
  - name: open-webui
    version: 3.1.6
    repository: https://helm.openwebui.com/
    condition: enbuildAI.ollama.enabled
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
    condition: lightning_features.operations_lightning.monitoring
  - name: headlamp
    version: 0.31.1
    repository: https://kubernetes-sigs.github.io/headlamp/
    condition: lightning_features.operations_lightning.headlamp
